{{- if .Values.queryEngine.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "laminar.resourceName" "query-engine-service" }}
spec:
  selector:
    app: {{ include "laminar.resourceName" "query-engine" }}
  ports:
    - protocol: TCP
      port: {{ .Values.queryEngine.service.port }}
      targetPort: {{ .Values.queryEngine.service.targetPort }}
  type: {{ .Values.queryEngine.service.type }}
{{- end }}
