{{- if .Values.appServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: app-server-service
spec:
  selector:
    app: app-server
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.appServer.service.port }}
      targetPort: {{ .Values.appServer.service.targetPort }}
  type: {{ .Values.appServer.service.type }}
---
{{- if .Values.appServer.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: app-server-load-balancer
  annotations:
    {{- range $key, $value := .Values.appServer.loadBalancer.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    app: app-server
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8080
    - protocol: TCP
      name: grpc
      port: 8443
      targetPort: 8001
  type: LoadBalancer
{{- end }}
{{- end }} 