{{- if .Values.appServerConsumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-consumer
  labels:
    app: app-server-consumer
spec:
  replicas: {{ .Values.appServerConsumer.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app-server-consumer
  template:
    metadata:
      labels:
        app: app-server-consumer
    spec:
      containers:
        - name: app-server-consumer
          image: {{ .Values.images.repository }}/{{ .Values.images.appServer.name }}:{{ .Values.images.appServer.tag }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.appServerConsumer.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1
          env:
            - name: OPERATION_MODE
              value: "consumer"
            - name: PORT
              value: {{ .Values.appServerConsumer.env.port | quote }}
            - name: CONSUMER_PORT
              value: {{ .Values.appServerConsumer.env.consumerPort | quote }}
            - name: DATABASE_MAX_CONNECTIONS
              value: {{ .Values.appServerConsumer.env.databaseMaxConnections | quote }}
            - name: NUM_SPANS_WORKERS
              value: {{ .Values.appServerConsumer.env.numSpansWorkers | quote }}
            - name: NUM_BROWSER_EVENTS_WORKERS
              value: {{ .Values.appServerConsumer.env.numBrowserEventsWorkers | quote }}
            - name: NUM_PAYLOAD_WORKERS
              value: {{ .Values.appServerConsumer.env.numPayloadWorkers | quote }}
            - name: NUM_TRACE_SUMMARY_WORKERS
              value: {{ .Values.appServerConsumer.env.numTraceSummaryWorkers | quote }}
            - name: NUM_EVALUATORS_WORKERS
              value: {{ .Values.appServerConsumer.env.numEvaluatorsWorkers | quote }}
            - name: NUM_NOTIFICATION_WORKERS
              value: {{ .Values.appServerConsumer.env.numNotificationWorkers | quote }}
            - name: NUM_CLUSTERING_WORKERS
              value: {{ .Values.appServerConsumer.env.numClusteringWorkers | quote }}
            - name: RABBITMQ_MAX_CHANNEL_POOL_SIZE
              value: {{ .Values.appServerConsumer.env.rabbitmqMaxChannelPoolSize | quote }}
            - name: REDIS_URL
              value: {{ .Values.appServerConsumer.env.redisUrl }}
            - name: ENVIRONMENT
              value: {{ .Values.global.environment }}
            - name: AGGREGATE_TRACES
              value: {{ .Values.appServerConsumer.env.aggregateTraces | quote }}
            - name: ENABLE_TRACING
              value: {{ .Values.appServerConsumer.env.enableTracing | quote }}
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: CLICKHOUSE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLICKHOUSE_URL
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLICKHOUSE_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AWS_REGION
            - name: S3_TRACE_PAYLOADS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: S3_TRACE_PAYLOADS_BUCKET
            - name: SHARED_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SHARED_SECRET_TOKEN
            - name: AEAD_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AEAD_SECRET_KEY
            - name: ONLINE_EVALUATORS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ONLINE_EVALUATORS_SECRET_KEY
            - name: PYTHON_ONLINE_EVALUATOR_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PYTHON_ONLINE_EVALUATOR_URL
            - name: TRACE_SUMMARIZER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TRACE_SUMMARIZER_SECRET_KEY
            - name: TRACE_SUMMARIZER_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TRACE_SUMMARIZER_URL
            - name: TRACE_EVENT_IDENTIFIER_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TRACE_EVENT_IDENTIFIER_URL
            - name: SLACK_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SLACK_ENCRYPTION_KEY
            - name: CLUSTER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLUSTER_ENDPOINT
            - name: CLUSTER_ENDPOINT_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLUSTER_ENDPOINT_KEY
            - name: DATABASE_SSL_ROOT_CERT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_SSL_ROOT_CERT
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                - {{ .Values.global.nodeGroupName }}
{{- end }}
