{{- if .Values.appServer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-server-nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log info;
    pid /var/run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {

      client_max_body_size 25M;

      # Standard HTTP log format
      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
      
      # Regular HTTP server for path-based routing
      server {
        listen 8080;
        access_log /var/log/nginx/access.log main;
        
        # Forward only /v1/* requests
        location ~* ^/v1/ {
          proxy_pass http://localhost:{{ .Values.appServer.env.port }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_buffering off;
          proxy_http_version 1.1;
          chunked_transfer_encoding on;
        }
        
        # Health check endpoint
        location /health {
          proxy_pass http://localhost:{{ .Values.appServer.env.port }};
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
        
        # Return 404 for all other paths
        location / {
          return 404;
        }
      }
    }
{{- end }} 