{{- if .Values.appServerConsumer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: app-server-consumer-service
spec:
  selector:
    app: app-server-consumer
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.appServerConsumer.service.port }}
      targetPort: {{ .Values.appServerConsumer.service.targetPort }}
  type: {{ .Values.appServerConsumer.service.type }}
{{- end }}
