{{- if .Values.clickhouse.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  labels:
    app: clickhouse
spec:
  type: {{ .Values.clickhouse.service.type }}
  ports:
    - port: {{ .Values.clickhouse.service.port }}
      targetPort: {{ .Values.clickhouse.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.clickhouse.service.nativePort }}
      targetPort: {{ .Values.clickhouse.service.nativePort }}
      protocol: TCP
      name: native
  selector:
    app: clickhouse
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-headless
  labels:
    app: clickhouse
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.clickhouse.service.port }}
      targetPort: {{ .Values.clickhouse.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.clickhouse.service.nativePort }}
      targetPort: {{ .Values.clickhouse.service.nativePort }}
      protocol: TCP
      name: native
  selector:
    app: clickhouse
{{- end }} 