{{- $cloudProvider := .Values.global.cloudProvider | default "aws" -}}
{{- if and .Values.frontend.enabled .Values.frontend.ingress.enabled (eq $cloudProvider "aws") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "laminar.resourceName" "frontend-alb" }}
  annotations:
    {{- if .Values.frontend.ingress.annotations }}
    {{- range $key, $value := .Values.frontend.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- else }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    {{- end }}
    {{- if and .Values.frontend.ingress.externalDns.enabled .Values.frontend.ingress.hostname }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.frontend.ingress.hostname }}
    {{- end }}
spec:
  {{- if .Values.frontend.ingress.className }}
  ingressClassName: {{ .Values.frontend.ingress.className }}
  {{- else }}
  ingressClassName: alb
  {{- end }}
  rules:
    {{- if .Values.frontend.ingress.hostname }}
    - host: {{ .Values.frontend.ingress.hostname }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "laminar.resourceName" "frontend-service" }}
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
