{{- if .Values.quickwit.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "laminar.resourceName" "quickwit" }}
  labels:
    app.kubernetes.io/name: quickwit
    app.kubernetes.io/instance: quickwit
    app.kubernetes.io/version: {{ .Values.quickwit.version | quote }}
{{- end }}
