{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "laminar.resourceName" "rabbitmq" }}
spec:
  replicas: {{ .Values.rabbitmq.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "laminar.resourceName" "rabbitmq" }}
  serviceName: {{ include "laminar.resourceName" "rabbitmq-headless" }}
  {{- if .Values.rabbitmq.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "laminar.resourceName" "rabbitmq-data" }}
      spec:
        storageClassName: {{ .Values.rabbitmq.persistence.storageClass | default (include "laminar.resourceName" .Values.storage.storageClass.name) }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.rabbitmq.persistence.size | quote }}
  {{- end }}
  template:
    metadata:
      name: {{ include "laminar.resourceName" "rabbitmq" }}
      labels:
        app: {{ include "laminar.resourceName" "rabbitmq" }}
    spec:
      serviceAccountName: {{ include "lmnr.secrets.serviceAccountName" . }}
      initContainers:
        - name: "rabbitmq-config"
          image: busybox:latest
          volumeMounts:
            - name: rabbitmq-config
              mountPath: /tmp/rabbitmq
            - name: rabbitmq-config-rw
              mountPath: /etc/rabbitmq
          command:
            - sh
            - -c
            - cp /tmp/rabbitmq/rabbitmq.conf /etc/rabbitmq/rabbitmq.conf && echo '' >> /etc/rabbitmq/rabbitmq.conf;
              cp /tmp/rabbitmq/enabled_plugins /etc/rabbitmq/enabled_plugins
      volumes:
        - name: rabbitmq-config
          configMap:
            name: {{ include "laminar.resourceName" "rabbitmq-config" }}
            optional: false
            items:
              - key: enabled_plugins
                path: "enabled_plugins"
              - key: rabbitmq.conf
                path: "rabbitmq.conf"
        - name: rabbitmq-config-rw
          emptyDir: {}
        {{- if not .Values.rabbitmq.persistence.enabled }}
        - name: {{ include "laminar.resourceName" "rabbitmq-data" }}
          emptyDir: {}
        {{- end }}
        {{- if include "lmnr.secrets.awsEnabled" . }}
        - name: secrets-store-aws
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: lmnr-secrets-aws
        {{- end }}
        {{- if include "lmnr.secrets.vaultEnabled" . }}
        - name: secrets-store-vault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: lmnr-secrets-vault
        {{- end }}
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      containers:
        - name: rabbitmq
          image: {{ .Values.images.rabbitmq.repository }}:{{ .Values.images.rabbitmq.tag }}
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
          volumeMounts:
            - name: rabbitmq-config-rw
              mountPath: "/etc/rabbitmq"
            - name: {{ include "laminar.resourceName" "rabbitmq-data" }}
              mountPath: "/var/lib/rabbitmq/mnesia"
            {{- if include "lmnr.secrets.awsEnabled" . }}
            - name: secrets-store-aws
              mountPath: "/mnt/secrets-store-aws"
              readOnly: true
            {{- end }}
            {{- if include "lmnr.secrets.vaultEnabled" . }}
            - name: secrets-store-vault
              mountPath: "/mnt/secrets-store-vault"
              readOnly: true
            {{- end }}
          envFrom:
            {{- include "lmnr.secrets.envFrom" . | nindent 12 }}
          ports:
            - name: amqp
              containerPort: {{ .Values.rabbitmq.service.amqpPort }}
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
            - name: epmd
              containerPort: 4369
              protocol: TCP
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "status"]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 15
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 10
      {{- include "laminar.nodeSelector" (dict "service" .Values.rabbitmq "global" .Values.global) | nindent 6 }}
      {{- include "laminar.affinity" (dict "service" .Values.rabbitmq "global" .Values.global) | nindent 6 }}
      {{- include "laminar.tolerations" (dict "service" .Values.rabbitmq "global" .Values.global) | nindent 6 }}
{{- end }}
