{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laminar.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
  annotations:
    {{- include "laminar.annotations" . | nindent 4 }}
data:
  enabled_plugins: |
    [rabbitmq_peer_discovery_k8s, rabbitmq_management].
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend = k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.k8s.service_name = rabbitmq-headless

    queue_master_locator=min-masters

    max_message_size = {{ .Values.rabbitmq.config.maxMessageSize | int }}
{{- end }} 