{{- if include "lmnr.secrets.awsEnabled" . }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lmnr-secrets-aws
  labels:
    {{- include "laminar.labels" . | nindent 4 }}
  annotations:
    {{- include "laminar.annotations" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.secrets.awsSecretsManager.region | quote }}
    objects: |
      - objectName: {{ include "lmnr.secrets.awsSecretName" . | quote }}
        objectType: secretsmanager
        jmesPath:
          {{- range .Values.secrets.awsSecretsManager.secretKeys }}
          - path: {{ . | quote }}
            objectAlias: {{ . | quote }}
          {{- end }}
  secretObjects:
    - secretName: app-secrets-aws
      type: Opaque
      data:
        {{- range .Values.secrets.awsSecretsManager.secretKeys }}
        - objectName: {{ . | quote }}
          key: {{ . | quote }}
        {{- end }}
{{- end }}
