{{- if and (include "lmnr.secrets.awsEnabled" .) .Values.secrets.awsSecretsManager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secrets.awsSecretsManager.serviceAccount.name }}
  labels:
    {{- include "laminar.labels" . | nindent 4 }}
  annotations:
    {{- include "laminar.annotations" . | nindent 4 }}
    {{- if .Values.secrets.awsSecretsManager.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.secrets.awsSecretsManager.serviceAccount.roleArn }}
    {{- end }}
{{- end }}
