{{- if include "lmnr.secrets.vaultEnabled" . }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lmnr-secrets-vault
  labels:
    {{- include "laminar.labels" . | nindent 4 }}
  annotations:
    {{- include "laminar.annotations" . | nindent 4 }}
spec:
  provider: vault
  parameters:
    vaultAddress: {{ .Values.secrets.vault.address | quote }}
    roleName: {{ .Values.secrets.vault.role | quote }}
    vaultKubernetesMountPath: {{ .Values.secrets.vault.authPath | quote }}
    {{- if eq .Values.secrets.vault.kvVersion "v2" }}
    vaultKVMountPath: "secret"
    vaultKVVersion: "2"
    {{- else }}
    vaultKVMountPath: "secret"
    vaultKVVersion: "1"
    {{- end }}
    objects: |
      {{- range .Values.secrets.vault.secretKeys }}
      - objectName: {{ . | quote }}
        secretPath: {{ $.Values.secrets.vault.secretPath | quote }}
        secretKey: {{ . | quote }}
      {{- end }}
  secretObjects:
    - secretName: {{ include "laminar.resourceName" "app-secrets-vault" }}
      type: Opaque
      data:
        {{- range .Values.secrets.vault.secretKeys }}
        - objectName: {{ . | quote }}
          key: {{ . | quote }}
        {{- end }}
{{- end }}
