apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.storageClass.name }}
provisioner: {{ .Values.storage.storageClass.provisioner }}
parameters:
  type: {{ .Values.storage.storageClass.type }}
reclaimPolicy: {{ .Values.storage.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storage.storageClass.volumeBindingMode }}
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/zone
        values:
          {{- range .Values.storage.storageClass.zones }}
          - {{ . }}
          {{- end }} 