{{- $cloudProvider := .Values.global.cloudProvider | default "aws" -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "laminar.resourceName" .Values.storage.storageClass.name }}
provisioner: {{ .Values.storage.storageClass.provisioner | default (eq $cloudProvider "aws" | ternary "ebs.csi.aws.com" "pd.csi.storage.gke.io") }}
parameters:
  type: {{ .Values.storage.storageClass.type | default (eq $cloudProvider "aws" | ternary "gp3" "pd-balanced") }}
reclaimPolicy: {{ .Values.storage.storageClass.reclaimPolicy | default "Retain" }}
volumeBindingMode: {{ .Values.storage.storageClass.volumeBindingMode | default "WaitForFirstConsumer" }}
{{- $showTopologies := false -}}
{{- if .Values.storage.storageClass.zones -}}
  {{- $showTopologies = true -}}
  {{- if and (eq $cloudProvider "gcp") (eq (len .Values.storage.storageClass.zones) 1) (eq (index .Values.storage.storageClass.zones 0) "us-east-1b") -}}
    {{- $showTopologies = false -}}
  {{- end -}}
{{- end -}}
{{- if $showTopologies }}
allowedTopologies:
  - matchLabelExpressions:
      {{- if eq $cloudProvider "aws" }}
      - key: topology.ebs.csi.aws.com/zone
      {{- else if eq $cloudProvider "gcp" }}
      - key: topology.gke.io/zone
      {{- else }}
      - key: topology.kubernetes.io/zone
      {{- end }}
        values:
          {{- range .Values.storage.storageClass.zones }}
          - {{ . }}
          {{- end }}
{{- end }}
